name: A-MAORM Build Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          # We use YOUR_DOCKER_USERNAME directly here to avoid the secret error
          username: aiswaryareddy71
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          # If your Dockerfile is in the main folder, change './backend' to '.'
          context: .
          push: true
          tags: aiswaryareddy71/amaorm-backend:latest