name: A-MAORM Build Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          # Updated to match your Docker Desktop screenshot
          username: aiswarya64
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          # Using '.' ensures it finds the Dockerfile in your folder
          context: .
          push: true
          tags: aiswarya64/amaorm-backend:latest